### ISSUE TITLE
Ipad

### ISSUE THREAD

**Issue by jarodium** [williammustaffa/jquery.dad.js#11]
Hello
It is not working for me in Ipad.

**Comment by williammustaffa** [comment]
Hi, 

The touch functionality isn't ready yet.
I'll work on it soon and update this issue status.

Thanks for the report.

**Comment by acebruin** [comment]
Any ETA on this William? We're currently using the plugin on production. Works great! Would love it even more if it works on mobile devices. Thanks!

**Comment by williammustaffa** [comment]
I don't have any ETA for this feature, but i'll update this ticket when it's ready.

**Comment by williammustaffa** [comment]
The plugin now supports touch.

**Comment by williammustaffa** [comment]
@acebruin and @jarodium

Please take a look and reopen if needed.

EDIT:

Not working on ipad yet. I'll fix this today.

LAST EDIT:

Fixed and tested.
