### ISSUE TITLE
How do i get the index of an element when its dropped?

### ISSUE THREAD

**Issue by Mitsaras1911** [williammustaffa/jquery.dad.js#12]

**Comment by williammustaffa** [comment]
You can get it on the addDropzone callback. Once 'e' will be your dropped element, it'll have two data-attributes containing positioning info.

``` javascript
myDad.addDropzone('.dropzone',function(e){
  var initial_index = e.attr("data-dad-id");
  var current_index = e.attr("data-dad-position");
});
```

Hope it helps.

**Comment by Mitsaras1911** [comment]
Thanks 

Dimitris Christodoulou

**Comment by Mitsaras1911** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Dimitris

Confirm that you know Dimitris: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=nkGoGq4l&invitationId=6140104529141645312&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eioih71j9%7Eql








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ioih71j9-ql&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEh_51vagzcogAAAVTYIk04c-c5bQtEzCw1uc2dUSM9JGCc8Es0o7fyOmtAJF2V3wGCAjvLVGgP1TeId7LTk3KSQU_A-wSXPaFl711tmOtQhyyrjzKdNXSR-PFDsQvJsg3YQmyg80MYEWZzgmThMNS7t9nGeA3ApC0sv6d8OlHlxfm6bZ0C8rWNNI5Qs54MUgH_&eid=0-ioih71j9-ql


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ioih71j9-ql&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Mitsaras1911** [comment]
Dimitris Christodoulou would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-o723re-iooaeli2-wq&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=nkGoGq4l&invitationId=6140104529141645312

View Dimitris Christodoulou&#39;s profile: https://www.linkedin.com/e/v2?e=-o723re-iooaeli2-wq&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=nkGoGq4l&invitationId=6140104529141645312





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-o723re-iooaeli2-wq&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-o723re-iooaeli2-wq&loid=AQFmQn5fipVEQgAAAVTtzOQryOkMpRFNiIDRveKTyVL0VpVRR4tawyDkVjFSTe-L_5JaTeAt5Zm0g7R_iInhM86G8AvO75WM6U6eG6hNlMxYx9zySHb5AZuOdKoafyVLmm5ErHQ16warZfQvMOl5uQbqx6wgZU1zll9mixcZsCv_FM6CGZiUj19qB_WIlolGcEU7

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-o723re-iooaeli2-wq&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Mitsaras1911** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend dc.christodoulou.tepak has been using DigitalOcean – a
cloud hosting service designed just for developers – and thought you
might want to give it a shot. You can deploy a server in 55 seconds from
our control panel or use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=4ff9bd666b9539&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>
