### ISSUE TITLE
Bug with horizontal scrolling

### ISSUE THREAD

**Issue by Lerdouille** [williammustaffa/jquery.dad.js#22]
Hi,

thank you first for this amazing plugin.
It's more like a feature request than a bug, i would like to have the possibility to have every draggable component on a unique row.

If there are a huge number of divs (about 100) i would like to put everything in a single row with a horizontal scrollbar.

I tried to use a float left attributes and a fixed size of the elements, i also added the css values for overflow-x, but even if i saw a good scrollbar, when i want to drag some elements a the end there is a bug due certainly to a translation not calculated correctly.

Best regards

**Comment by williammustaffa** [comment]
Hey,

Sorry for the delay. I'm gonna check this issue as I was able to reproduce it here, also I'm considering it a bug hence the elements position is affected. Thanks for the feedback!

Regards

**Comment by williammustaffa** [comment]
Hey @Lerdouille,

The issue should be fixed now. Check latest release.
Please reopen this issue in case you still facing it.
