### ISSUE TITLE
"Events" section's content error should be fixed

### ISSUE THREAD

**Issue by aben-sky** [williammustaffa/jquery.dad.js#23]
The following has been corrected:

## Events

Events are provided to handle the drag and drop actions such as drag start, drag end, drop... See below:

### dadDragStart

Event triggered when user starts dragging an element.

```

$(".my-container").on("dadDragStart", function (e, targetElement) {
  // do your thing here
})

```

### dadDragUpdate

Event triggered when the current dragged element has its position updated.

```

$(".my-container").on("dadDragUpdate", function (e, targetElement) {
  // do your thing here
})

```

### dadDragExchange

Event triggered when the containers exchange children.

```

$(".my-container").on("dadDragExchange", function (e, sourceContainer, targetContainer) {
  // do your thing here
})

```

### dadDragEnd

Event triggered when user drops an element, this event is triggered before the dropping animation.

```

$(".my-container").on("dadDragEnd", function (e, targetElement) {
  // do your thing here
})

```

### dadDrop

Event triggered when the element is dropped, this event is triggered after the dropping animation.

```

$(".my-container").on("dadDrop", function (e, droppedElement) {
  // do your thing here
})

```

**Comment by williammustaffa** [comment]
My bad! Thanks for noticing. This has been fixed :)
